# Generated by Django 2.2.7 on 2020-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciconnect',
            fields=[
                ('ci_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ciconnect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crawlrecord',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_keyword', models.CharField(max_length=255)),
                ('cr_num', models.IntegerField()),
                ('cr_time', models.DateTimeField()),
                ('cr_status', models.IntegerField()),
                ('cr_check', models.IntegerField()),
            ],
            options={
                'db_table': 'crawlrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('f_path', models.CharField(max_length=255)),
                ('f_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filerecord',
            fields=[
                ('fr_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_id', models.CharField(max_length=255)),
                ('fr_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'filerecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_title', models.CharField(max_length=255)),
                ('i_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'instrument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_name', models.CharField(max_length=255)),
                ('r_id', models.IntegerField()),
                ('r_flag', models.IntegerField()),
                ('q_status', models.IntegerField()),
                ('q_check', models.IntegerField()),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=255)),
                ('u_pwd', models.CharField(max_length=255)),
                ('u_email', models.CharField(max_length=255)),
                ('u_phone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
